### ISSUE TITLE
Add vertical bar or dot on chart in the landing page Monthly coverage worldwide chart

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#101]
Currently the Monthly coverage worldwide chart doesn't have an indication of which datum on the line chart you have selected when you scrub over the chart.

![Screenshot 2019-05-02 at 12 31 20](https://user-images.githubusercontent.com/424620/57069917-3769ea00-6cd6-11e9-9b88-cc52f37f7554.png)

We should add either a vertical bar aligned to the date the user has selected or maybe make a dot appear on the line in the position currently selected by the user.

cc @holantonela @elioqoshi

**Comment by sarathms** [comment]
@holantonela The added bar looks like this.
![image](https://user-images.githubusercontent.com/700829/60025122-ff907a80-9666-11e9-9a2f-b2eb75a6b699.png)

Alternatively, there is another way of doing this by adding a horizontal bar, effectively a crossbar at the cursor.
![image](https://user-images.githubusercontent.com/700829/60025284-5007d800-9667-11e9-8e57-3175f5d0b3a5.png)

Interaction-wise, first one is snappy because it is Voronoi based. The second one is fluid and doesn't snap.

**Comment by holantonela** [comment]
It is great! Could we have dotted light grey lines? I think we want to have a dot, too. I'm looking at the docs and seems possible. @hellais what do you think?
https://formidable.com/open-source/victory/docs/victory-voronoi-container/

**Comment by sarathms** [comment]
Like this?
![image](https://user-images.githubusercontent.com/700829/60043533-4e9dd600-968e-11e9-9db0-c37a3f2aa884.png)

Will look into rendering a dot at the highlighted point.

**Comment by holantonela** [comment]
> Like this?
Yes!
> Will look into rendering a dot at the highlighted point.
Awesome, thanks!

**Comment by hellais** [comment]
@sarathms is it possible to make the line "snap" to the point you are selecting?

Currently as I move around the cursor it's actually displaying in the tooltip some values which are not exactly the ones selected by the cursor.

**Comment by hellais** [comment]
My last comment still needs to be addressed in https://github.com/ooni/explorer/pull/205 or a new PR.
