### ISSUE TITLE
Search page - All Web Connectivity measurements incorrectly say "OK"

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#113]
On the Search page, all Web Connectivity measurements say "Error" (in addition to all being colour-coded as orange, regardless of the actual results). 

![error](https://user-images.githubusercontent.com/8290574/57090662-998f1300-6d07-11e9-8998-c6ceebf26780.png)

They should in fact say "anomaly", or "accessible", or "blocked" (or "error"), depending on the result of each measurement.

**Comment by sarathms** [comment]
This is a known bug in the API for some time now. Related issues:
https://github.com/ooni/api/issues/59 (closed)
https://github.com/ooni/pipeline/issues/112#issuecomment-476188316

It is expected to work as expected when the API starts returning correct responses. But since we haven't tested it visually, on the explorer page, let's keep this issue open until it starts working.

**Comment by hellais** [comment]
This is fixed by instead showing OK thought it may in fact be error. I am renaming this issue and moving it to icebox.

**Comment by hellais** [comment]
I believe this has been fixed with the latest improvements to the fastpath and pipeline.

If that is not the case let's open another issue.
