### ISSUE TITLE
Search page - Consistently show the full tested URL

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#114]
When viewing Web Connectivity results from the Search page, some measurements show the tested URL (e.g. https://imageshack.com), while others show the tested domain (e.g. www.gmch.org). For example:

![urls-vs-domains](https://user-images.githubusercontent.com/8290574/57090922-423d7280-6d08-11e9-8dc2-6d3586122009.png)

Please display tested URLs consistently across all measurements.

**Comment by hellais** [comment]
@holantonela what do you think of this?

**Comment by hellais** [comment]
I think the quick and easy way to do this is to just display the full URL (with no styling) wether it is HTTP or HTTPS.

**Comment by sarathms** [comment]
I have removed the styling for `https` URLs. Instead of showing the full URL which can get quite long in some cases, I have now truncated them properly and added a tooltip which shows the full URL.

![image](https://user-images.githubusercontent.com/700829/62804358-052d0d00-babb-11e9-8538-0395e693b469.png)

**Comment by holantonela** [comment]
It looks good. Is done for me.
