### ISSUE TITLE
Display country flag in measurement pages

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#116]
Perhaps we can add the country flag next to the country name within the measurement pages?

![country-flag](https://user-images.githubusercontent.com/8290574/57091453-841ae880-6d09-11e9-80e8-873e1b688f83.png)

That way, when people share screenshots of these pages, you can easily/visually see which country it pertains to (from the image of the flag).

**Comment by sarathms** [comment]
Addressing this in #183 

This is how it looks like right now. @holantonela Do you think this needs to be done differently?
![image](https://user-images.githubusercontent.com/700829/59040409-9b874d00-8844-11e9-8ba8-baa7dba53ccc.png)

**Comment by hellais** [comment]
cc @holantonela

**Comment by holantonela** [comment]
Thanks @sarathms for working on it. Following the mocks, we should have this order: 

1. Country
2. Network Name 
3. ASN
4. Time and Date

That will allow us to have a mobile view like the following screenshot, which has better alignment.
![Screen Shot 2019-06-07 at 10 54 05](https://user-images.githubusercontent.com/7602174/59109019-a14b6400-8912-11e9-9868-0638f22a38a0.png)

For @hellais's concern, I'd consider adding a white background to the flag container. Since you have a `3px` padding, we will have 3px of a white border. Maybe the label `Country` is redundant. What do you think @hellais?

![Screenshot_2019-06-07 OONI Explorer(2)](https://user-images.githubusercontent.com/7602174/59109474-7f9eac80-8913-11e9-8ab8-7f5e587131fc.png)

Meanwhile you are working on it, maybe you can close #171 :)

**Comment by sarathms** [comment]
Opened #211 to address this.

**Comment by hellais** [comment]
> Maybe the label Country is redundant. What do you think @hellais?

imho we should drop the flag altogether in this iteration and reconsider introducing it with a more visible pattern. I think with the flag being so small it doesn't really add that much value and I find it unbalances the layout of the page especially on desktop.

I suggest we drop it altogether, but file an issue to consider re-adding it in the future (or maybe keep this open and rename it).
