### ISSUE TITLE
Provide a way for the ooni-explorer users to communicate mistakes and false positives/negatives

### ISSUE THREAD

**Issue by anadahz** [ooni/explorer#213]
Short for a report button that marks reports from users as potential false positive/negative.
Adding a static text on the report page such as:

```
If you think this report is a false positive/negative please email us, discuss this on our mailing list, ..."
```

Ideally (maybe a separate issue) have a function that gathers all the false positives/negatives tags as voted by the users and based on that improves the filter queries.

**Comment by agrabeli** [comment]
Community members may come across sites that they aren't able to access. Perhaps it's clear to them that the specific site is blocked (because, for example, a block page is served), or perhaps it's unclear if the site is intentionally blocked.

In addition to testing the site in question with OONI Probe, perhaps we can add a feature to OONI Explorer that enables community members to propose URLs for testing (if they suspect they're blocked). And perhaps the URLs that are proposed are then forwarded to the Citizen Lab test lists.
