### ISSUE TITLE
Performance test results are not shown in the overview page

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#217]
As reported by @agrabeli in: https://github.com/ooni/explorer/issues/123.

![Screenshot 2019-07-18 at 17 58 22](https://user-images.githubusercontent.com/424620/61473223-46337500-a986-11e9-90f2-51d46a5c9e3f.png)

The performance test results bars are missing from the test coverage chart in the main page.

**Comment by sarathms** [comment]
The bars for tests with less measurements weren't missing. They just stay as invisible as they were before hiding other tests with a bigger share of measurement count. 

The problem is that we weren't updating the domain (based on `testCoverageMaxima`) for the stack chart which is computed adding up counts from all `test_group`s.

**Comment by sarathms** [comment]
After the fix:
![image](https://user-images.githubusercontent.com/700829/61894164-d2412180-aedd-11e9-8d24-96b3e340bdd9.png)

![image](https://user-images.githubusercontent.com/700829/61894195-e553f180-aedd-11e9-86c7-f18b51edce9a.png)

**Comment by hellais** [comment]
Ah yes I see what you mean. I have checked with the latest deployed version and it works well as expected.
