### ISSUE TITLE
Wireframes for country profile pages

### ISSUE THREAD

**Issue by gabelula** [ooni/explorer#26]
First and second iteration for wireframes for the country profile pages. 

Related to https://github.com/ooni/explorer/issues/10

**Comment by holantonela** [comment]
hey all!

I draw some ideas to think how users can navigate this page. I like the idea of having a Table of Contents as a sub-navigation menu. We can discuss cons and pros for each layout, but basically, we need a layout that contemplates on the first sight:

1. an overview  
2. a table of contents menu 
3. if a report of that country is available, then we should highlight it and have a [download] button

Based on the questions Maria listed for us, I made a first inventory of the cards that we should have here. I set up an order, but I'm open to run a card sorting exercise to define hierarchies. Each number acts as a Section, and Cards are going to live inside each Section.


![wireframes-layout1](https://user-images.githubusercontent.com/7602174/50294644-1acec300-0455-11e9-950d-5d4888ef932c.png)
![wireframes-cards1](https://user-images.githubusercontent.com/7602174/50294641-186c6900-0455-11e9-91dd-526211738774.png)


[DRAFT]
### Table of Contents
    1. Overview
    2. Manipulation Detected? 
        2.1 /IF Confirmed or Anomalies
        Positive Measurements
            - **Card: Confirmed Blocked Sites List**
                - Title: qty blocked sites
                - List of blocked sites (should we set up a qty, let's say 5 or 10? if yes, how we can show the most relevant first?)
                - Quote about the category of blocked sites
                - Top blocker ASNs (?)
                - View All > 
            - **Card: Anomaly Detected Sites List**
                - Title
                - List
                - Quote about category
                - View All >
            - **Card: Search input for specific URL**
                - check if this site was blocked in the country 
            - **Card: Blocked IM apps**
                - Title
                - Top Blocker ASNs
                - View All >
            - **Card: No Blocked IM App** 
            - **Card: Positive Middleboxes**
                - Title
                - Top Blocker ASNs
                - View All >
        2.2 /IF Nothing detected
        Negative Measurements
            - Card or Quote (?)
    3. Access to information
            - **Card: Circumvention Tools Blocked** or
            - **Card: Circumvention Tools Available**
                - Title
                - Top blocker ASNs
                - View All >
            - **Card: Middleboxes Detected**
                - Title
                - Vendor(s)
                - Top ASn's with tampering detected
                - Quote about how it changed over time (?)
                - View All >
            - **Card: Speed and Performance**
                - Title
                - Media Upload and Download
                - Number of measured ASN vs. total ASN
                - NDT or DASH Data suggesting throttling
                - View All >
    4. Measurement Stats - I'd like to reinforce the community effort on this section and also encourage users to run probe. We will work on this flow after we finish Countries.
            - **Card: Qty of Measurements**
                - Title
                - Line graph - comparison over time
                - Donut chart - comparison with the total of measurements
            - **Card: Kind of Measurements**
                - Title
                - Chart - qty of measurements per test
            - **Card: ASN Coverage**
                - Title
                - Comparison Total n of ASNs vs. ASNs Measured over time
            - **Card: Top Measured ASN**
                - Title
                - List of top measured ASNs
                - View All
    5. Contextual Country info
        - Network landscape
        - Internet penetration
        - Relevant laws & regulations
        - Reported cases of internet censorship

I'm still thinking about if we should allow users to customize the country view by selecting a timeframe for all the data displayed at the page or it could be better/doable enable users to do it per card? "Last Month," "Last Year," "Lifetime" seems good for me. If we need "Last 6 Months", is good too.

**Comment by elioqoshi** [comment]
Thanks @holantonela !

@Others: I synced today with Antonela and reviewed wireframes among others. Please find 4 different directions for the layouts of the Country Pages, based on Antonela's sketches. These wireframes are a bit truthful to the scale and layout than the handwritten sketches I assume but as you can see from the sketch style, it's very rough and should just provide an idea of how things can be laid out.

The views are on Figma:
https://www.figma.com/proto/JleNvmgzX5ewk6RCUPg2RXCR/Design-Guidelines?node-id=194%3A374&viewport=592%2C150%2C0.0402206&scaling=min-zoom

(Page 5 is just page 4 with a collapsed header).
You can comment on different parts of the wireframes in Figma by going to the top left of the menu bar or pressing (C). 

I will circle back with Antonela on the wireframes beginning of January after the holidays. I'd like to invite you to chime in with your thoughts on which layout you'd envision to be more fitting for the country pages. Some input from my end on each wireframe direction:

## Direction A (Page 1)
This is using a very similar layout to the measurement pages and would basically recycle that. While it would keep the layout experience similar to the measurement pages, I believe we would lose a nice opportunity to impress with all the data and information OONI has.

## Direction B (Page 2)
This is designed to have a fixed 1/3 sidebar with overview information over that country, as well as a navigation menu to jump to the desired section of the country page. The rest 2/3 of the width is reserved for the actual content and can be populated with the various graphs and content we want to include. The header would also include a CC0 Photo of that country with a OONI blue overlay (similar to how the photos in the research reports were included). I think this is one of my preferred layouts to move forward with as it has a good amount of white space and flows in well vertically.

## Direction C (Page 3)
This is very similar to Direction B but with a few differences.
- The header is full width and also includes the country flag.
- The various sections within the content will be shown on cards (light gray background to differentiate between cards). 
I slightly prefer B to this but the differences are subtle.

## Direction D (Page 4 & 5)
This is the most experimental direction which could be the creme de la creme of the new Explorer if done right, but it might be also a bit risky in my opinion. @holantonela suggested adding this direction as it gives more of a curated feel, based on an 'editorial style' with a lot of breathing space utilizing white space to bring the attention to the most important elements of that country overview. When collapsed (scrolled) the header would shrink (Page 5) and stay sticky with the content exposed in cards below. The navigation of the header would help the viewer navigate quickly through content.

----

I hope this input from my end helps to understand the context better. To move forward with the actual content, we would need to agree on the "Inventor" of the page, which @holantonela listed so well in the comment above. @agrabeli @hellais could you have a quick review if the rough outline of that inventory makes sense and do changes accordingly? The better we pin this down at this point the easier the mockup design process will be later.

**Comment by hellais** [comment]
@holantonela great work!

Here is some feedback:

> if a report of that country is available, then we should highlight it and have a [download] button

Not all our reports are available in pdf format (actually most of them are not) and for some countries we have multiple publications some of which are full length research reports and some are shorter blog posts.
We should be sure to support presenting all the country relevant OONI publication on the country profile page and not just pdf reports.

> List of blocked sites (should we set up a qty, let's say 5 or 10? if yes, how we can show the most relevant first?)

Maybe we can use the alexa popularity ranking to establish which sites to prioritise?

On this topic, though, I think it's most useful to have a listing of the categories of sites that are blocked (and maybe just 1 or 2 sample sites for each category) in the overview section.

In countries that have say 1000+ blocked websites, it's most useful to a visitor to know that "Country X blocks Gambling, File sharing & Blogs" than to know the exact number of sites blocked or which ones they are.

> Top Blocker ASNs

If I understand this correctly, I am not 100% sure we are going to be able to say something of this sort.

I would say that rather than ranking the ASNs (or networks) we could simply say in each of the relevant categories something like "We found sites of categories Gambling, File sharing & Blog to be blocked in AS1, AS2".

The reason why ranking is tricky is that we may not have enough measurements for a certain AS and it's tricky to determine how many measurements are enough to conclude that a given ASN is **not** blocking a certain site.


> NDT or DASH Data suggesting throttling

This is a very nice to have thing, yet we don't currently have data for it.

> Measurement Stats

I love how you rationalised this section and the line of thought in here.

**Comment by agrabeli** [comment]
Thanks @holantonela! The Table of Contents and general proposed layout is very well thought out and looks great! :) 

Most of the initial feedback that came to mind is similar to what @hellais already wrote, particularly his comments on ranking ASNs based on blocking & our current inability to infer throttling from NDT and DASH data. 

Other than that, here are some other thoughts:

1. I really like that the results (confirmed/blocked vs. accessible) are separately presented in dedicated cards/sections for website and IM testing. Why are circumvention tools & middleboxes though included under a separate "Access to information" section? Perhaps we can lump circumvention tools under the same sections as websites & IM apps (since their testing would also render "blocked" or "accessible" results)? And perhaps middleboxes could be nested there as well, though the values they render are "detected" or "not detected" (referring to middleboxes/network tampering), so perhaps they should be presented separately? Not sure.

2. "Measurement Stats - I'd like to reinforce the community effort on this section and also encourage users to run probe." => Couldn't agree more! <3

3. I like your idea of filtering the data based on the time-frame, this is also currently supported on OONI Explorer (and goes back to the first measurement ever collected by OONI Probe). On this note, I generally think it will be useful to be able to filter the data based on (1) time-frame, (2) OONI Probe test, (3) ASN, (4) Category (if the Web Connectivity test is selected), (5) Single URL (and, if possible, set of URLs). Being able to filter based on ASN is particularly important (everyone has been asking for this, and I would benefit from this feature too), while being able to filter based on category codes would enable research & journalistic work.

4. List of blocked sites => Perhaps we can prioritize on showing the most recently blocked sites? @hellais I think people may be more interested in learning which sites are currently (or more recently) blocked, though I do see the value in displaying more popular sites (based on Alexa rankings) as well.

5. The contextual country info will probably be missing for most countries (at least during the first months following the launch). I would therefore recommend not highlighting that section too much (to reduce community disappointment). :)

**Comment by agrabeli** [comment]
Thanks @elioqoshi for working on this and for sharing detailed explanations! :) Unfortunately though I'm unable to see your work through the Figma link you shared (it appears to point to the OONI design system color palette). Can you please re-share the Figma link?

**Comment by elioqoshi** [comment]
@agrabeli @hellais I'm not sure what happened there, this link should work:
https://www.figma.com/proto/Z6PtVLW7YkqcTRIRsO2Qzg/Explorer-Country-Pages?node-id=194%3A377&viewport=367%2C279%2C0.289624&scaling=scale-down-width&redirected=1

You can navigate to the other pages with the arrow keys or the bottom navigation when you hover over it.

**Comment by agrabeli** [comment]
Thanks @elioqoshi for sharing the Figma link and for working on this. Overall, great job! 

My feedback:

1. What type of information would be displayed in the "Overview stats" boxes at the top? Would those boxes be clickable, taking you to a separate page, or would they be graphs? 

2. I like the idea of having the menu of items displayed on the left side of the page (and therefore have a preference for the first 3 pages). 

3. "No manipulation/censorship" is missing as a section (following "manipulation", per @holantonela's sketches and ToC). 

4. How would the user filter the measurements? One of the most important features of the (current) OONI Explorer country pages is being able to filter all OONI measurements. How would this be supported in the new country pages?

5. I think it would be good to both show the country highlights and present a filter at the start of the page, so that it's clear and simple to users that they can filter the measurements to find what they're interested in.

Since these wireframes are based on @holantonela's sketches and ToC, I guess the same questions that I previously asked also apply here.

Thanks again!

**Comment by agrabeli** [comment]
@elioqoshi Regarding the Table of Contents, I'd propose the following changes:

1. Include cards on **circumvention tools** under the "Blocked" and "Not blocked" categories (1 & 2), and remove them from the "Access to information" section.

2. Re-name section 3 ("Access to information") to "Network characteristics" (for now => perhaps we can think of a better title at a later stage). Having removed the circumvention tools from this section, this section would only include results pertaining to middleboxes, NDT & DASH data.

3. When clicking on each of the cards under sections 1, 2 & 3 => Include ASN information, displaying in which networks those results have been collected from. For example: "https://torproject.org is blocked in AS8048, AS6303, + 200 more" (or something of the sort). 

Excluding my comments on filters (which I now know are being included in the new Search page), did you have any questions based on my previous feedback?

**Comment by elioqoshi** [comment]
Here a very rough draft of the country page more fleshed out in sections: https://www.figma.com/proto/Z6PtVLW7YkqcTRIRsO2Qzg/Explorer-Country-Pages?node-id=292%3A0&viewport=-128%2C543%2C0.0996821&scaling=min-zoom

I was not able to do as much progress as I hoped today as it's quite complex (I only did the first 3 sections)

Please note:

- The navigation bar would be sticky
- The main thing I need help with is with data points for many of the tables and stats, but I hope this might start stir something up about potential things we could show. Please highlight anything which might be completely off.
- Not happy with the hero section as it's too much white space. Do you have any other suggestions what could go in there? Otherwise I will change the layout a bit.
- If you see something I missed already in your feedback, please bare with me until I get there (I feel a bit overwhelmed with all these sections at once, so focusing on the first 3 sections might be best for now) 

P.S: I think one needs a Figma account to comment on there :confused:
Types of Measurements was something I came up with. It's supposed to work similar to this interactive prototype:
https://www.figma.com/proto/Z6PtVLW7YkqcTRIRsO2Qzg/Explorer-Country-Pages?node-id=174%3A507&viewport=-128%2C543%2C0.0996821&scaling=min-zoom (edited) 
Some more explorations (not really asking for feedback here) on lists, with hover and tooltips:

https://www.figma.com/proto/Z6PtVLW7YkqcTRIRsO2Qzg/Explorer-Country-Pages?node-id=179%3A0&viewport=-11%2C822%2C0.787484&scaling=min-zoom (edited)

**Comment by hellais** [comment]
I really like the way this is going!

For starters, I would suggest we try to keep these mockups still at bit of a higher level of details (i.e. not so high resolution as they are now), so that we can

Some feedback on these mocks:

1. I think that the "Types of measurements" chart is not the most important bit of information and probably it's not something we want to have at all.

Ideally the types of measurements for every country are going to be evenly split across the measurement types (or if we are overcounting websites, which we would if we just do the measurement count).

My suggestion is to drop this chart as it's not really that useful.

2. I like the top level highlights in the section headings, though I am not so convinced by the choice of stats
What is the `N/M` Networks?
What is the measurement rate?

3. It would be great if for website we could include the breakdown of categories of websites that are known to be confirmed blocked

4. We should include in the websites section the notion of "confirmed blocked" (which is different from anomalies)

5. For the website we should quantify the number of measurements that present anomalies and the number of network that show a certain result for a given site

6. As mentioned in the feedback above Circumvention doesn't go in the information control section

**Comment by agrabeli** [comment]
Thanks @elioqoshi for designing this wireframe, it looks great!

In addition to @hellais feedback (which touches upon many of the points I also wanted to make), I have the following feedback:

1. Perhaps the menu items (overview, manipulation, etc.) could go on the left side of the page (similarly to the 1st wireframe mockup you previously shared), thus eliminating the extra white space?

2. The "Accessible" section is missing from the menu items (and from the sections below), as pointed out in my previous feedback.

3. Perhaps the results can also be filtered based on the previous week as well? I suspect this may be of interest to many community members, particularly when they're tracking ongoing censorship events, and allows them to narrow the results to a shorter time-frame. 

4. As proposed in my previous feedback, perhaps "Information Access" can tentatively be renamed to "Network characteristics"? We can potentially edit this again later on (at the copy-writing stage), but I think saying "Network characteristics" will reduce ambiguity for the upcoming usability studies.

5. Perhaps "Measurement Quality" can tentatively be renamed to "Measurement Stats"? Same reasoning as point 4.

6. "Types of Measurements" => Perhaps here we can include similar stats to those previously included in the original country page mockups, showing the types of websites blocked, which networks are covered, etc. But since we have an entire "Measurement Stats" section further below, perhaps we can also omit this altogether.

7. I would like to re-iterate @hellais point about the importance of showing both (a) anomalous websites and (b) confirmed blocked websites. 

8. Websites table (under Manipulations section) => The elements in the header of the table don't correspond to the elements displayed inside the table. For example, under "Test categories", it says "Networks covered". 

9. If we're presenting the website data in aggregate (@hellais please confirm), then perhaps the Websites table can include the following data: URL, Category, ASNs, Anomaly count, Last Time Accessible, More details (where the user can click to get all the anomalous measurments pertaining to that URL?).

10. Perhaps the IM table can include the following data: Apps, ASNs, Anomaly count, Last Time Accessible, More details (quite similarly to Websites).

11. As proposed in my previous feedback, perhaps the Circumvention Tool results can go under the Manipulation section (and be removed from the Information Access section)? In which case, the Information Access section would only have middleboxes, NDT & DASH.

@hellais @holantonela I'm thinking that having an entire section for showing the accessible websites, apps, and circumvention tools may not be that interesting (and we risk losing users before they scroll down all the way to middleboxes, performance, etc.). Perhaps all results (blocked, anomalous, accessible) could be presented in 1 table per category, which users can filter? We could automatically show the blocked/anomalous first (when users land on the page), providing them the ability to filter for accessible measurements from the same tables. What do you think?

**Comment by elioqoshi** [comment]
Thanks for the quick turnaround on the feedback!

>I think that the "Types of measurements" chart is not the most important bit of information and probably it's not something we want to have at all.

++

> I like the top level highlights in the section headings, though I am not so convinced by the choice of stats. 

I don't have a clear idea of exactly which stats to show there, so as I said, treat them more as placeholders to show some information we deem important. They are applicable to the selected time period ('All time' in this case_ on the top of the page.

Though for the sake of completeness, explaining what I had in mind for these:

> What is the N/M Networks? 

In how many networks out of all networks in this country, web connectivity tests with anomaly results have been run.

> What is the measurement rate?

On average, how many measurements of this test group are run in networks of this country by users (so basically =[Total Measurements Run in this Time Period] / [Selected Time Period in Days]  )

Data is not my forte and I have no real world experience with OONI data so I'd appreciate some suggestions of data stats you think would suit here.

---

> It would be great if for website we could include the breakdown of categories of websites that are known to be confirmed blocked

Similar to the Types of Measurements Donut Chart? I think that might not work as there are too many categories to represent with colors. A simple horizontal column chart should do it for a start though.

> We should include in the websites section the notion of "confirmed blocked" (which is different from anomalies)

++

> For the website we should quantify the number of measurements that present anomalies and the number of network that show a certain result for a given site

Sorry, I'm not sure if I understood what you mean with this. Could you elaborate?

> As mentioned in the feedback above Circumvention doesn't go in the information control section

You are right, I missed that.

> I guess quite a fair amount of stuff is still missing here, so maybe it's useful to do another round of feedback once it's more fleshed out.

Yeah, I thought it would be more helpful (for me at least) to check in more often with smaller chunks of progress since the page might be too complex to digest at once.

**Comment by elioqoshi** [comment]
> 1. Perhaps the menu items (overview, manipulation, etc.) could go on the left side of the page (similarly to the 1st wireframe mockup you previously shared), thus eliminating the extra white space?

Yeah that was the other pattern I wanted to try as well. Not sure how that would eliminate white space rather than add more to it since the navigation would take 1/3 or 1/4 of the body width leaving respectively 2/3 or 3/4 to the actual content, whereas in this past iteration, the full width would be available for the actual content. It might work better, but there will definitely be more white space and more vertical scrolling.

> 2. The "Accessible" section is missing from the menu items (and from the sections below), as pointed out in my previous feedback.

Will check again.

> 4. Perhaps the results can also be filtered based on the previous week as well? I suspect this may be of interest to many community members, particularly when they're tracking ongoing censorship events, and allows them to narrow the results to a shorter time-frame.

Sure, will add that.

> 5. As proposed in my previous feedback, perhaps "Information Access" can tentatively be renamed to "Network characteristics"? We can potentially edit this again later on (at the copy-writing stage), but I think saying "Network characteristics" will reduce ambiguity for the upcoming usability studies.

Thanks for highlighting this, will rename this.

> 5. Perhaps "Measurement Quality" can tentatively be renamed to "Measurement Stats"? Same reasoning as point 4.

++

>6.  "Types of Measurements" => Perhaps here we can include similar stats to those previously included in the original country page mockups, showing the types of websites blocked, which networks are covered, etc. But since we have an entire "Measurement Stats" section further below, perhaps we can also omit this altogether.

Omitting this as suggested by @hellais. We can revisit this at a later stage whether it would make sense.

> 8. Websites table (under Manipulations section) => The elements in the header of the table don't correspond to the elements displayed inside the table. For example, under "Test categories", it says "Networks covered".

I was afraid this would be the impression. It's actually not a table header, but just a section with some high level stats of that test group. I should try to make it clearer that they are separate (maybe by adding an actual table header)

>9.  If we're presenting the website data in aggregate (@hellais please confirm), then perhaps the Websites table can include the following data: URL, Category, ASNs, Anomaly count, Last Time Accessible, More details (where the user can click to get all the anomalous measurments pertaining to that URL?).

Exploring that and updating the mockups.

> 10. Perhaps the IM table can include the following data: Apps, ASNs, Anomaly count, Last Time Accessible, More details (quite similarly to Websites).

++ Same here

> 11. As proposed in my previous feedback, perhaps the Circumvention Tool results can go under the Manipulation section (and be removed from the Information Access section)? In which case, the Information Access section would only have middleboxes, NDT & DASH.

Sounds good, will do.

**Comment by holantonela** [comment]
@elioqoshi great start!
 
Some comments:

- Let's keep it on wireframe level. Typography is ok. The color choices for those header elements needs review. Let's focus on content and hierarchies at this stage so we can iterate quickly and we don't get loose in the details.

- I'd suggest you don't paginate on this page. A View All button will move the user to the result page of the respective query. If is necessary to show more, we can have a Show more extension with one click and then, the second click can move the user to the results page.

- Let's focus on improving the way users digest our data. A numbered list of most popular five blocked sites based on Alexa Top Sites is a more visually appealing way to show positive blocking per country. The data displayed in tables gives to the row data the same hierarchy on all columns. We can remove the table layout and highlight the more relevant content.

- I'd like to see some iterations for the general state cards. The full-width row now looks like the table header. Let's explore a col6 and a col4 versions.

Maria and Arturo gave enough feedback, we could have a review tomorrow.

**Comment by hellais** [comment]
> In how many networks out of all networks in this country, web connectivity tests with anomaly results have been run.

Hum. I fear that this stats is going to be quite misleading, because: a) It's hard to quantify exactly how many network there are in a country b) Even if we do quantify it all these networks may not necessarily be usable by users.

I would suggest dropping this stat at least at the level of per test group. We can include something related to this in the measurement quality section, though.

> On average, how many measurements of this test group are run in networks of this country by users (so basically =[Total Measurements Run in this Time Period] / [Selected Time Period in Days] )

This is also quite tricky to and can result in being misleading. For example the websites tests are going to always have a higher rate, because with a tap of the button the user will have run many more measurements. It's also dependent on the speed of the network and it's likely to be a pretty 
unstable metric.

> Similar to the Types of Measurements Donut Chart? I think that might not work as there are too many categories to represent with colors. A simple horizontal column chart should do it for a start though.

For these I would suggest not using a pie chart, but rather just presenting (without a chart) the list of categories (without quantities) for which we found sites to be blocked.

> For the website we should quantify the number of measurements that present anomalies and the number of network that show a certain result for a given site
> Sorry, I'm not sure if I understood what you mean with this. Could you elaborate?

Example:
www.google.com was measurement 10 times on ASN1 and 5 of those measurements show anomalies, 0 confirmed,5 OK, it was measured 20 times on ASN2 and 0 of those measurements show anomalies,20 confirmed,0 OK, it was measured 15 times on ASN3 and 15 of those measurements show anomaly, 0 confirmed and 0 OK.

I would like to have in the section for `www.google.com`, the indication:
ASN1: 5 anomaly, 0 confirmed, 5 OK
ASN2: 0 anomaly, 20 confirmed, 0 OK
ASN3: 15 anomaly, 0 confirmed, 0 OK

As we discussed in the call we should limit this to maybe the top 3 most measured ASNs.

**Comment by holantonela** [comment]
@elioqoshi I think this @agrabeli's idea is 👌.
>  Perhaps all results (blocked, anomalous, accessible) could be presented in 1 table per category, which users can filter? We could automatically show the blocked/anomalous first (when users land on the page), providing them the ability to filter for accessible measurements from the same tables. What do you think?

**Comment by hellais** [comment]
I am going to recap here as well my latest feedback on: https://www.figma.com/proto/Z6PtVLW7YkqcTRIRsO2Qzg/Explorer-Country-Pages?node-id=296%3A119&viewport=-4939%2C1837%2C0.693457&scaling=min-zoom

Things I really liked:

• The pills for the blocked categories are really neat

• The sticky side bar

Feedback/comments:

1. 🎏It's very important that results are presented on a per network basis. This applies to all the categories of tests. See as an example of this the initial country page mockups: https://xd.adobe.com/spec/2f585e0f-1a7e-4f6c-41f9-fa411520998e-5969/screen/03270981-207b-4a23-a289-868cf2188ea5/Country-Page/

2. We should prominently display OONI research reports if we have them for the country
 
3. The confirmed measurement count are missing in the URL sections

4. I think we should drop the stats headers as we don't have any useful stats to show there

5. The middlebox results should be presented as booleans (found a middlebox on this network or we didn't) which are enrichable with more details as our heuristcs improve (we found a middlebox which is by vendor squid)

6. It would be great if the URL section supported filtering and searching by:
 - URL 
 - Number of anomalous measurements
 - Networks
 - Category codes

7. I don't think it makes sense to use tables to present the results of anything except the URL measurements (and even there maybe a table is also not appropriate)

**Comment by agrabeli** [comment]
I agree with @hellais latest feedback.

@hellais @elioqoshi @holantonela I think I may be confused, but I'd like to flag an issue and seek clarification. Where will the Accessible results (for websites, IM apps, circumvention tools) be displayed? How will the users find these results? Would they have to search for them via the Search page, or will they be displayed in the country page as well? If so, how?

I suspect that displaying all Accessible results per category (websites, IM apps, circumvention tools) will lead to the creation of a super-long country profile page, and users will have to scroll a lot until they finally reach the middlebox and performance results. Not displaying the Accessible results though (like in the latest Figma) means that users are missing essential pieces of the story.

Would it make sense to have 1 table per category, where you can filter the results of that table based on:

* Blocked
* Anomalies
* Accessible

Note: The distinction between "Blocked" and "Anomalies" is only applicable for websites.

If the above proposal makes sense, then perhaps the table can, by default, present the "blocked"/"anomalous" results, listed from the most recent, and that the Accessible only appear if you filter that table.

What do you think?

**Comment by hellais** [comment]
The link to the latest mocks is: https://www.figma.com/file/Z6PtVLW7YkqcTRIRsO2Qzg/Explorer-Country-Pages?node-id=855%3A14837
