### ISSUE TITLE
Replace "im" with "IM" in measurement coverage by test class graph

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#268]
The Measurement Coverage by Test Class graph available in all OONI Explorer country pages includes legends which explain each OONI Probe test class. 

However, when hovering over the bars within the graph, "im" (presented in the pop-up black label) does not correspond to any of the provided legends.

I therefore propose:

1. Replace "im" with "IM"
2. Add "(IM)" next to the legend "Instant Messaging", so that it's clear what we're referring to in the graph.

**Comment by sarathms** [comment]
@agrabeli does #269 also address the same thing?

**Comment by hellais** [comment]
I think we should have what appears in the bubble be the same as the legend.

@sarathms is it easy to align what is in the bubble to what is in the legend (i.e. "Instant Messagging", "Middleboxes", etc.)?

**Comment by sarathms** [comment]
It is not as straight forward as it looks. The problem is that we use [internationalized components](https://github.com/ooni/explorer/blob/master/components/test-info.js#L20) to display test (group) names everywhere on the site right now. These don't work inside the dynamic tooltip in the chart.

Two solutions I can think of:
1. Add static English-only strings of names to the `testGroups` map and use them in such contexts. This is easy to do, but the problem is that texts in legend and tooltip will again diverge in other language contexts.
```
name: <FormattedMessage id='...',
nameStr: 'Websites',
```

2. Using the non-imperative `intl.formatMessage()` API to create another map for names which will return strings that can be used. This *might* add complexity but works well in all cases.
```
websites: intl.formatMessge({id: 'Tests.Groups.Webistes.Name'}),
im: ...
```

Sounds like `2` is a better way to go.
