### ISSUE TITLE
Group test names by test group

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#277]
It was suggested at CCC that we group test names by the test group to make it easier for people to find measurements for the test they care about.
![Screenshot 2019-08-29 at 12 20 55](https://user-images.githubusercontent.com/424620/63932585-c0f8b100-ca57-11e9-9fed-94eec4a1c98a.png)

This can simply be a matter of grouping the `<select><option>` into a `<optgroup>`.

For example we would have: `web_connectivity` be under the `websites` group and `facebook_messenger`, `telegram`, `whatsapp` in the `instant messagging` group.

**Comment by agrabeli** [comment]
@hellais yes, agreed - this is great feedback. This would also help consolidate the experience with the apps, where users are exposed to test groups (rather than test names). If I recall correctly, we wanted to group the test names under test groups as part of the initial mockups, but this was not implemented in the end because it was unclear how to do it nicely from a design-perspective. It would be great if we could re-think how to design this.

**Comment by hellais** [comment]
> but this was not implemented in the end because it was unclear how to do it nicely from a design-perspective. It would be great if we could re-think how to design this

As mentioned above we are going to opt in the first iteration for using a very simple `<optgroup> ` which is part of the HTML standard and does not require any specific design work (the element is not styleable).

No further design discussion or work is necessary to carry out the implementation of this issue.
