### ISSUE TITLE
Fix filter for tested URLs in country page

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#281]
When exploring the measurements on the Websites section on the ET country page, I clicked on "Explore more measurements" under a tested URL (http://africanarguments.org/). I expected to get re-directed to the Search page and only view measurements filtered based on that URL.

Instead, I was re-directed to the Search page including what appears to be a random list of measured URLs (not filtered based on http://africanarguments.org/). See: https://explorer-beta.ooni.io/search?test_name=web_connectivity&probe_cc=ET&probe_asn=24757&input=http%3A%2F%2Fafricanarguments.org&since=2019-08-03&until=2019-09-02

![random-urls](https://user-images.githubusercontent.com/8290574/64129421-2a602300-cdbc-11e9-9e57-3597840ab86b.png)

This probably needs to be fixed so that the user is re-directed to the Search page containing only measurements pertaining to the selected URL.

**Comment by agrabeli** [comment]
@sarathms @hellais I think this should be solved before we launch.

**Comment by sarathms** [comment]
Looks like this is a problem at the API end. Searching with `input` parameter seems to be broken.

[Search link using `domain`](https://explorer-beta.ooni.io/search?until=2019-09-03&probe_cc=NG&test_name=web_connectivity&since=2019-08-18&domain=notjustok.com&probe_asn=37148) works as expected.

[Search link using `input`](https://explorer-beta.ooni.io/search?until=2019-09-03&probe_cc=NG&test_name=web_connectivity&since=2019-08-18&input=notjustok.com&probe_asn=37148) should have worked earlier. Shows irrelevant results.

@hellais Can you confirm?

**Comment by hellais** [comment]
@sarathms it's an explorer issues.

Looking at the network inspector explorer is making a query with no input parameter:
![Screenshot 2019-09-03 at 19 15 57](https://user-images.githubusercontent.com/424620/64194379-4973b900-ce7f-11e9-84db-0f076529b182.png)

**Comment by sarathms** [comment]
Another question in the context of #274 (Replace 'input' with 'domain') is how we handle the `Websites` section where we show URLs and not just domains. We cannot use the `domain` field when building the `Explore more measurements` search link because it wouldn't be accurate.

But when we retain the `input` field like before, it wouldn't help populate the `Domain` field in the sidebar, when you follow the `Explore more msmts` button.

**Comment by sarathms** [comment]
> perform the query to the backend with the domain field instead of the input field though

So we are OK with showing more measurements in the search page when we click on the `Explore` button for e.g 'http://bbc.com/some/story' because the search page would show everything with `domain=bbb.com`

**Comment by hellais** [comment]
I think the better of two evils is to link to the query with the domain field.

Ideally we would have also a URL field in the search box with API support for searching by URL (see: https://github.com/ooni/api/issues/52).

**Comment by hellais** [comment]
> So we are OK with showing more measurements in the search page when we click on the Explore button for e.g 'http://bbc.com/some/story' because the search page would show everything with domain=bbb.com

Without making changes to the search page I think this is the only way to go about doing it for the time being. 

Otherwise we are linking users to a page where they are not able to edit the search criteria which is not ideal.
