### ISSUE TITLE
Add call to action to download OONI Probe when no data is available

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#291]
It was suggested by a community member that it would be useful to add a call to action on the country pages when no data is available.

In general we should also sprinkle call to actions to download OONI Probe in various other pages too.

**Comment by agrabeli** [comment]
@hellais this is excellent feedback, couldn't agree more. 

In addition to an "Install OONI Probe" button, we may also want to include an OONI Run button so that people can coordinate testing when they're not physically in the country that they wish to get measurements from (for example, someone checks out the Burkina Faso country page and sees that there are no measurements for the resources they care about -- they can be instructed to generate and share an OONI Run link with their contacts in that country).

Perhaps the copy for these things could be something in the lines of:

"No data is currently available. 

Are you in X country? Install OONI Probe to contribute measurements.

Otherwise, generate an OONI Run link and share it with your contacts in X country."

**Comment by agrabeli** [comment]
Just came across this ticket which is very relevant and a really cool thing to do: https://github.com/ooni/explorer/issues/22

**Comment by sarathms** [comment]
I am going to add a markdown-formatted (with links) string to pick up from the copy. Do we have any ideas for more specific UI elements to use here?
