### ISSUE TITLE
Improve validation of the date field

### ISSUE THREAD

**Issue by xhdix** [ooni/explorer#313]
## Expected Behavior
Show error like error in `Domain` Input

## Actual Behavior
Part of the JavaScript function crashes, and the page needs to be refreshed.

## Steps to Reproduce the Problem

  1. manually change the date

## Console Logs
```
/_next/static/style.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
commons.5370dd4583a0552fb768.js:1 usage of fontSizeMult will be deprecated
o @ commons.5370dd4583a0552fb768.js:1
commons.5370dd4583a0552fb768.js:1 usage of fontSizeMult will be deprecated
o @ commons.5370dd4583a0552fb768.js:1
commons.5370dd4583a0552fb768.js:1 usage of fontSizeMult will be deprecated
o @ commons.5370dd4583a0552fb768.js:1
commons.5370dd4583a0552fb768.js:1 usage of fontSizeMult will be deprecated
o @ commons.5370dd4583a0552fb768.js:1
commons.5370dd4583a0552fb768.js:1 usage of fontSizeMult will be deprecated
o @ commons.5370dd4583a0552fb768.js:1
commons.5370dd4583a0552fb768.js:1 usage of fontSizeMult will be deprecated
o @ commons.5370dd4583a0552fb768.js:1
commons.5370dd4583a0552fb768.js:1 usage of fontSizeMult will be deprecated
o @ commons.5370dd4583a0552fb768.js:1
commons.5370dd4583a0552fb768.js:1 usage of fontSizeMult will be deprecated
o @ commons.5370dd4583a0552fb768.js:1
commons.5370dd4583a0552fb768.js:1 usage of fontSizeMult will be deprecated
o @ commons.5370dd4583a0552fb768.js:1
commons.5370dd4583a0552fb768.js:1 usage of fontSizeMult will be deprecated
o @ commons.5370dd4583a0552fb768.js:1
commons.5370dd4583a0552fb768.js:1 usage of fontSizeMult will be deprecated
o @ commons.5370dd4583a0552fb768.js:1
--------------------------------------
commons.5370dd4583a0552fb768.js:1 TypeError: a.utc is not a function
    at Object.onChange (search.js:1)
    at t.<anonymous> (search.js:1)
    at au (commons.5370dd4583a0552fb768.js:1)
    at ru (commons.5370dd4583a0552fb768.js:1)
    at Wu (commons.5370dd4583a0552fb768.js:1)
    at Vu (commons.5370dd4583a0552fb768.js:1)
    at commons.5370dd4583a0552fb768.js:1
    at Object.KqkS.t.unstable_runWithPriority (commons.5370dd4583a0552fb768.js:1)
    at Ci (commons.5370dd4583a0552fb768.js:1)
    at ki (commons.5370dd4583a0552fb768.js:1)
    at zi (commons.5370dd4583a0552fb768.js:1)
    at Re (commons.5370dd4583a0552fb768.js:1)
    at Ie (commons.5370dd4583a0552fb768.js:1)
    at zn (commons.5370dd4583a0552fb768.js:1)
    at commons.5370dd4583a0552fb768.js:1
    at Object.KqkS.t.unstable_runWithPriority (commons.5370dd4583a0552fb768.js:1)
    at qi (commons.5370dd4583a0552fb768.js:1)
    at Pn (commons.5370dd4583a0552fb768.js:1)
    at HTMLDocument.r (commons.5370dd4583a0552fb768.js:1)
(anonymous) @ commons.5370dd4583a0552fb768.js:1
--------------------------------------
style.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

```

**Comment by hellais** [comment]
I believe this is related to lack of validation in the from and until fields.

Since this issue was filed some minimal validation was added (for example you cannot filter by something which is clearly not a date, like a set of random characters), however it still fails when you input something like `201910` which is accepted as a date by the client-side validation code, but not by the API backend.

I think what we should do for this is:
* [ ] Only accept strings which are valid dates according to the OONI API
* [ ] When the data is wrong show an error below the input box which failed validation (similarly to how we do for the Domain field)
* [ ] Handle server-side API errors better

I think this is not a too hard of an issue to pickup by somebody interested in a first issue, so I am adding the relevant tags.

**Comment by xhdix** [comment]
@hellais I think @sarathms  has solved this. I am right?

**Comment by hellais** [comment]
> I think @sarathms has solved this. I am right?

To some extent some validation has been added, however there are still some cases which are not handled properly.

For example:

https://explorer.ooni.org/search?until=2019-11-19&since=201901

results in:

![Screenshot 2019-11-19 at 10 01 54](https://user-images.githubusercontent.com/424620/69132126-c512f880-0ab3-11ea-8fbe-bcd4be1d032e.png)

**Comment by hellais** [comment]
This is done.
