### ISSUE TITLE
Kickoff brainstorm about highlights page 

### ISSUE THREAD

**Issue by gabelula** [ooni/explorer#32]
Schedule a meeting between UX team and OONI to brainstorm what should be done of the highlights page.

**Comment by agrabeli** [comment]
Note: The comment below was originally posted here: https://github.com/ooni/explorer/issues/33

I'm thinking that requiring users to know that they have to click Search or Countries, then filter the measurements based on test names that they may not be familiar with, etc may be a bit too complicated.

The landing page offers the opportunity to inform users of what are some of the exciting types of things that they can expect to find on OONI Explorer.

Therefore, perhaps we can show users that they can expect to find data on (a) website blocking, (b) IM blocking, (c) circumvention tool blocking, (d) speed & performance of networks, (e) presence of middleboxes (on the landing page).

This, however, raises the following question: When navigating across sections (website blocking, IM blocking, etc) on the landing page, would those sections be clickable? If so, which page would they be redirected to?

Currently, users are required to search measurements by filtering them based on OONI Probe test names, which they may not be familiar with. Someone who's not familiar with OONI data and lands on OONI Explorer, may not even know that they are able to find data on website blocking, etc.

I think it's important that we (a) communicate this clearly and (b) enable thematic filtering of results (based on websites, IM apps, etc.) - rather than solely filtering results based on test names.

@hellais @elioqoshi @holantonela @sarathms thoughts?

![explorer-landing-page](https://user-images.githubusercontent.com/8290574/54443922-fc215500-4741-11e9-9b34-6620a8c44942.jpg)

**Comment by hellais** [comment]
This is done.
