### ISSUE TITLE
Implement the highlights page

### ISSUE THREAD

**Issue by gabelula** [ooni/explorer#33]
Implement the highlights page as the landing page of the new site

**Comment by gabelula** [comment]
Related to https://github.com/ooni/explorer/issues/2

**Comment by hellais** [comment]
This is effectively the landing page of OONI Explorer. A first iteration of this which is an MVP (doesn't include highlights) is implemented here: https://www.figma.com/file/OElUj1XR5SmbXUpWVzl8iton/OONI-Landing-Page?node-id=1%3A393.

cc @elioqoshi

**Comment by elioqoshi** [comment]
So are we getting rid of the highlights page? Renaming this issue then.

**Comment by agrabeli** [comment]
I'm thinking that requiring users to know that they have to click Search or Countries, then filter the measurements based on test names that they may not be familiar with, etc may be a bit too complicated.

The landing page offers the opportunity to inform users of what are some of the exciting types of things that they can expect to find on OONI Explorer. 

Therefore, perhaps we can show users that they can expect to find data on (a) website blocking, (b) IM blocking, (c) circumvention tool blocking, (d) speed & performance of networks, (e) presence of middleboxes (on the landing page).

This, however, raises the following question: When navigating across sections (website blocking, IM blocking, etc) on the landing page, would those sections be clickable? If so, which page would they be redirected to? 

Currently, users are required to search measurements by filtering them based on OONI Probe test names, which they may not be familiar with. Someone who's not familiar with OONI data and lands on OONI Explorer, may not even know that they are able to find data on website blocking, etc.

I think it's important that we (a) communicate this clearly and (b) enable thematic filtering of results (based on websites, IM apps, etc.) - rather than solely filtering results based on test names.

@hellais @elioqoshi @holantonela @sarathms thoughts?

![explorer-landing-page](https://user-images.githubusercontent.com/8290574/54439935-122b1780-473a-11e9-9835-fdab536f2a64.jpg)

**Comment by hellais** [comment]
From the perspective of a beta it's ready for review.

**Comment by hellais** [comment]
I say we keep this issue open until all the highlights page work is complete (i.e. adding also the content for the highlights).

**Comment by agrabeli** [comment]
The content for the Highlights has been written.

**Comment by elioqoshi** [comment]
For reference, layout for the Highlights on the Landing page here on the Figma:
https://www.figma.com/file/OElUj1XR5SmbXUpWVzl8iton/Explorer-Landing-Page?node-id=0%3A1

That includes the mobile version as well.

**Comment by sarathms** [comment]
@elioqoshi  Are the horizontal dividers only supposed to show up on mobiles?
![image](https://user-images.githubusercontent.com/700829/56930361-69970400-6aaa-11e9-85a9-eec956af39e5.png)

**Comment by sarathms** [comment]
@holantonela Can you confirm if we want to have these dividers only on mobile or can we have it on desktop as well? Currently we are unable to do it as easily as with, say bootstrap (`class='hidden-sm'`). Depending on how important it is for UX, I will either write a temporary fix or a longer term solution for the design system we use.

**Comment by hellais** [comment]
I would say this is now done.
