### ISSUE TITLE
Improve the error message for 500 series errors

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#339]
When a query times out we currently just say "We encountered an error please try again or the change the filters to get different results".

We should look into mapping the specific gateway timeout errors to something that is a bit more helpful and possibly propose a query that is known to work and/or link to the ooni.org/data page providing more information on how to download OONI data.

**Comment by agrabeli** [comment]
@hellais @sarathms I propose that we add the following text as an error message (and remove the Octopus illustration, so that it's only present in the "No Results found" error pages):

Dear Oonitarian,

Thank you for using OONI Explorer!

Unfortunately OONI Explorer is currently experiencing performance issues, which we're working on fixing.  

In the meanwhile, please explore OONI measurements with different filters, or consider getting OONI data from the [OONI API](https://api.ooni.io/) or the [ooni-data Amazon S3 bucket](https://ooni.org/post/mining-ooni-data/). You can also set-up your own instance of the [OONI PostgreSQL MetaDB](https://github.com/ooni/sysadmin/blob/master/docs/metadb-sharing.md). 

Thanks for your patience, and apologies for the inconvenience!

~ OONI team.

**Comment by agrabeli** [comment]
@hellais As a side-note based on the above: I didn't include a link to a query that "always works" because I'm unsure which query works in all circumstances (given that I frequently come across 500 and 504 errors when querying OONI Explorer).
