### ISSUE TITLE
Fix zero state for country page when no measurements exist

### ISSUE THREAD

**Issue by hellais** [ooni/explorer#410]
Currently when I access a country page which has no measurements at all, the charts and page looks different from a country which has very few measurements.

Compare this:

![Screenshot 2020-02-25 at 11 04 28](https://user-images.githubusercontent.com/424620/75236934-cfcddf80-57be-11ea-9477-0216fc1689a4.png)

To this:
![Screenshot 2020-02-25 at 11 07 26](https://user-images.githubusercontent.com/424620/75237082-115e8a80-57bf-11ea-9d34-8a7445185aba.png)

This also affects the display of the "Install OONI Probe" call to action.

**Comment by jbonisteel** [comment]
I have compared: https://explorer.ooni.org/country/AQ?since=2024-01-29&until=2024-02-29 to https://explorer.ooni.org/country/TV?since=2024-01-29&until=2024-02-29 today and this issue looks fixed. I will follow up in person to make sure I am not missing anything, and then likely close this issue or document next steps.

**Comment by majakomel** [comment]
I'm confirming we can close this issue.
