### ISSUE TITLE
Remove/update obsolete NDT keys

### ISSUE THREAD

**Issue by bassosimone** [ooni/explorer#452]
The following screen lists what "advanced" variables we're showing that they should either be updated or removed. The parent discussion is https://github.com/ooni/probe/issues/1106.

<img width="436" alt="Screenshot 2020-04-15 at 16 51 43" src="https://user-images.githubusercontent.com/337298/79352361-0829a880-7f3a-11ea-9d20-9110ba556d65.png">

Specifically:

- [x] update packet loss to be retransmit rate
- [x] out of order is gone and we should not be showing it
- [x] max ping is now an estimate so maybe we tell it's an estimate or we remove it
- [x] timeout is gone and we should not be showing it

As @hellais mentioned, in https://github.com/ooni/probe/issues/1106 we will ask the more broad question, while here we're mostly concerned with fixing the view.

**Comment by sarathms** [comment]
This has been fixed in #456 Here's how ndt7 measurements are shown now ([link to page](https://explorer.ooni.org/measurement/20200902T210530Z_AS53338_EXFPrWOXS6CXYqvoLezhoAdggwYlhNhojdBEapLkXFqg4v2ubb)):
![image](https://user-images.githubusercontent.com/700829/93255732-4e449b80-f768-11ea-9039-dae394351381.png)


While older NDT measurements continue to show the deprecated keys (timeouts etc)
![image](https://user-images.githubusercontent.com/700829/93255887-8b109280-f768-11ea-94ac-82da2d53478b.png)
