### ISSUE TITLE
Collect feedback about Website Centric Stats page

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#525]
An experimental page that shows global stats and visualizations about a website across all countries. 
https://explorer.ooni.org/experimental/website

The idea is to play around with it and collect feedback about making it useful.

**Comment by agrabeli** [comment]
@sarathms it would be very useful to add a search tool for **filtering based on anomalies** (to easily find all the countries where anomalies were present for the tested site in the selected date range). :)

**Comment by agrabeli** [comment]
@sarathms As for the country pages (e.g. https://explorer.ooni.org/experimental/website/TR?since=2020-10-26&until=2020-11-26&axis_x=probe_cc&test_name=web_connectivity&input=thepiratebay.org&probe_cc=TR), I have the following feedback:

* Perhaps **change the size of the graph** so that it's easier to see the "anomalies" (organge) or "confirmed blocked" (red) counts visually in the chart?

* Perhaps add a **link to relevant OONI Explorer measurements** in each page? While I find it super useful to look at aggregates, it would also be useful to have quick/easy access to relevant OONI Explorer measurements in order to be able to check individual measurements and drill deeper.

**Comment by agrabeli** [comment]
Will it be possible in the future to get results for multiple domains at the same time (as opposed to only 1)?

**Comment by agrabeli** [comment]
It would also be great if (from a UI perspective) it were more obvious where users need to click in order to access the country page (it took me a bit of clicking around before I realized that by clicking on the graph, you can access the country page). Perhaps make the **country name** clickable instead? At least that's what I intuitively clicked first.

**Comment by majakomel** [comment]
Closing this as it's about the page that doesn't exist anymore. Website related data is now accessible on https://explorer.ooni.org/domains
