### ISSUE TITLE
experimental/website: allow searching for IP addresses

### ISSUE THREAD

**Issue by bassosimone** [ooni/explorer#532]
When I tried to do so, it told me "hey, you can only search for domain names". Sometimes also IP addresses are useful, so I would be very pleased if we can extend this specific view to also support searching by IPs.

**Comment by sarathms** [comment]
@bassosimone We already have this feature. It was merged in #367 which was approved by you :smile:. It was also deployed not too later than it was merged. Did you mean it should work a bit differently? I was able to type `8.8.8.8` in the field and get [these results](https://explorer.ooni.org/search?until=2021-03-24&since=2021-02-22&test_name=web_connectivity&domain=8.8.8.8).

**Comment by sarathms** [comment]
Seems same as #354

**Comment by hellais** [comment]
Yes I confirm that this in fact works in the current explorer. Closing.
