### ISSUE TITLE
RiseupVPN: filtering for anomalies fails

### ISSUE THREAD

**Issue by cyBerta** [ooni/explorer#581]
## Expected Behavior
Filtering anomalies for RiseupVPN should show results accordingly. 
e.g.  https://explorer.ooni.org/search?until=2021-04-23&since=2021-03-24&test_name=riseupvpn&probe_cc=IR
shows that the Provider API Server is blocked in Iran (in particular fetching a certificate from https://black.riseup.net/ca.crt is blocked). 
https://explorer.ooni.org/search?until=2021-04-23&since=2021-03-24&test_name=riseupvpn&probe_cc=IR&only=anomalies and
https://explorer.ooni.org/search?until=2021-04-23&since=2021-03-24&test_name=riseupvpn&only=anomalies should show these test results.

## Actual Behavior
None of those anomalous results are shown if filtering for anomalies is enabled.

## Steps to Reproduce the Problem
see above

**Comment by sarathms** [comment]
Thanks for reporting. This is happening because the backend doesn't yet identify anomalous measurements for `test_name=riseupvpn`. For now, I am going to disable the `Status` filter for this test (and maybe a couple of others). And later when @FedericoCeratto confirms that the API allows this, I will enable it again.
