### ISSUE TITLE
Feedback to improve MAT

### ISSUE THREAD

**Issue by sarathms** [ooni/explorer#624]
These are inputs from @agrabeli shared over Slack on Nov 9, 2021.

> * Please include the OONI logo right under the chart (so that it's always clear that this chart is based on OONI data, when shared on social media etc)
> * Please include the test type (e.g. WhatsApp) right on top of the chart (so that we don't need to show the filter buttons in the image)
> * Please include the country (e.g. Ethiopia) right on top of the chart (so that we don't need to show the filter buttons in the image)
> * Please insure that the first date displayed in the chart doesn't cross over the "axis x" writing

**Comment by agrabeli** [comment]
@sarathms thanks for addressing my feedback! The only item currently missing (which is actually quite important) is:

- Please include the test type (e.g. WhatsApp) right on top of the chart (so that we don't need to show the filter buttons in the image)

If, however, it involves the testing of a specific website, it would be great to display that website.

**Comment by sarathms** [comment]
This was done in #684
