### ISSUE TITLE
Ensure translation of country names and continents on OONI Explorer Countries page

### ISSUE THREAD

**Issue by agrabeli** [ooni/explorer#716]
The various country names, continents (as listed above), and the "Search for countries" field are untranslated. 

![countries](https://user-images.githubusercontent.com/8290574/160180910-fc94a5bd-6e2e-4159-b068-a0d119fefd48.png)

Sarath mentioned that we could potentially use the standard translation of countries from the browser for the country names (instead of requiring Transifex translators to translate every single country name), while keeping an eye out for how that translates for places like Taiwan and Hong Kong. 

We should probably add "Search for countries" to a string on Transifex though.

**Comment by hellais** [comment]
I think we should update country-util to support pulling in the translated country names from unicode cldr: https://github.com/unicode-org/cldr-json/tree/main/cldr-json/cldr-localenames-full/main

**Comment by thara003** [comment]
I would like to work on this.
Have a few questions.
1. How to work with transfix translators?
2. Is there any documentation for the same?

**Comment by hellais** [comment]
I think what should be done to implement this is the following:
1. Add support for generating translated country names inside of country-util: https://github.com/ooni/country-util
2. Depending on the selected language resolve the country name inside of country-util

While we are at it, we should update the country-util download script to fetch data from the new unicode repository (see: https://github.com/ooni/country-util/blob/master/scripts/download-data.py#L13).

I don't think any transifex interaction is necessary for this. Since all the country names are already translated by unicode, we shouldn't require our translators to duplicate all this work.

**Comment by majakomel** [comment]
This has been fixed: we're using Intl.DisplayNames from format.js which uses https://cldr.unicode.org/ as a source
